### ISSUE TITLE
Jitsi link in calendar is not working

### ISSUE THREAD

**Issue by BenoitTallandier** [Twake/Twake#1013]
**Describe the bug**
Creating a jitsi link on the calendar return a link with error

**To Reproduce**
1. Go to calendar
2. Create an event
3. Click on the camera button
4. Save
5. Open the event
6. Click on the jitsi link
7. See error

OR 
1. open this link https://chat.twake.app/bundle/connectors/jitsi/call/twake_event_042e4b16-1fc1-9515-bd0e-d1464ee839c5?twake_user=85abe8b8-b186-11e9-9721-0242ac120004&twake_group=85eea194-b186-11e9-826a-0242ac120004
2. See error

**Screenshots**
```{"error": "Route not found: "/bundle/connectors/jitsi/call/twake_event_042e4b16-1fc1-9515-bd0e-d1464ee839c5/""}```

**Comment by RomaricMourgues** [comment]
Done for next 'next release' :)
