### ISSUE TITLE
No mail notifications on messages or tasks with deadlines (RabbitMQ issue)

### ISSUE THREAD

**Issue by cheerios911** [Twake/Twake#348]
**Describe the bug**
When inviting a user to a workspace (self hosted version) i have no Issue sending them the invite/deleted from workspace mail, however any mail associated to projects/tasks/reminders do not generate.

**To Reproduce**
1. Go to any workspace and create a task
2. assign a deadline and the users associated to the task
3. save task
4. deadline passes and there is no notification or mail to remind anyone of the task or meeting at hand
5. The same works for missed messages.  user sends message to another user offline > user offline has no knowledge that the message was sent until they login to the site/app

**Expected behavior**
I would expect to get an email notification when a message is missed or I'm offline as well as for any task that I assigned a deadline too.

**Comment by RomaricMourgues** [comment]
Hello, can you check you are up to date ? https://doc.twake.app/installation#update-twake
- Task deadlines are working on SaaS and I don't see any reason why it would not work on your site (if invitation email is sent)
- For the reminder email, it is only sent after 12h not being on Twake and having unread messages. it can be related to #293

**Comment by cheerios911** [comment]
We installed the self hosted version as you guys made it available :) so it was for sure pretty buggy and we've just been testing since then.  Right now we've been applying the patches since we first installed.  I will see about loading a fresh instance and see if that solves this and update here.  

I think you are also right about 293, the 15 min timer would be a much better option in my opinion, 12 hours is just too long to have a proper response time.

Thanks Romaric, i really appreciate how your teams response time has been since you guys became open source.

**Comment by cheerios911** [comment]
Hi Romaric.  We've confirmed we've been running the latest version but we are still seeing only mail being sent for creation/deletion of a new workspace but are not seeing any mail for tasks assigned, calendar invites, reminders, etc.  I see in other tickets that I am not the only one that has this issue.  #354  - We've also loaded a fresh instance of the system and run into the identical issue.

> Task deadlines are working on SaaS and I don't see any reason why it would not work on your site (if invitation email is sent)

We agree with you however looking at the documentation and the configuration we are running properly, but this will not send.

**Comment by RomaricMourgues** [comment]
Thanks, this is not good. I think there is an issue with RabbitMQ (we use SQS in production).
RabbitMQ is managing a lot of things including managing the badges next to channels and sending emails. Both are working so it seems to be related to delayed tasks.
I cant find a way to list actives routes and tasks on a live Twake RabbitMQ, it could be a good step to know what is happening. Scheduled notifications are prefixed by "scheduled_notifications_".
We will investigate soon on this point thank you!

**Comment by objeni** [comment]
Please see this and give me a solution 

> Fatal error: Uncaught Swift_TransportException: Expected response code 220 but got an empty response in /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php on line 445
> 
> Swift_TransportException: Expected response code 220 but got an empty response in /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php on line 445
> 
> Call Stack:
>     0.0002     350744   1. {main}() /twake-core/bin/console:0
>     0.0730    3036152   2. App\App->runCli() /twake-core/bin/console:9
>     0.0730    3036608   3. Common\CommandsManager->run() /twake-core/app/App.php:139
>     0.0730    3038320   4. Common\CommandsManager->execute() /twake-core/app/Common/CommandsManager.php:27
>     0.0743    3055320   5. Twake\Core\Command\MailsQueueCommand->executeFromManager() /twake-core/app/Common/CommandsManager.php:46
>     0.0744    3055320   6. Twake\Core\Command\MailsQueueCommand->execute() /twake-core/app/Common/Commands/ContainerAwareCommand.php:27
>     8.4940    8566808   7. Twake\Core\Services\TwakeMailer->sendInternal() /twake-core/src/Twake/Core/Command/MailsQueueCommand.php:69
>     8.5156    9394736   8. Twake\Core\Services\TwakeMailer->sendHtml() /twake-core/src/Twake/Core/Services/TwakeMailer.php:100
>     8.5706   11126328   9. Swift_Mailer->send() /twake-core/src/Twake/Core/Services/TwakeMailer.php:168
>     8.5706   11126384  10. Swift_SmtpTransport->start() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php:65
>     8.6699   11133952  11. Swift_SmtpTransport->readGreeting() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:147
>    18.7576   11142176  12. Swift_SmtpTransport->assertResponseCode() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:358

**Comment by objeni** [comment]
and this is RabbitMQ logs 


> 2020-11-04 08:56:03.511 [info] <0.2509.0> accepting AMQP connection <0.2509.0> (172.18.0.2:34508 -> 172.18.0.6:5672)
> 
> 
> 2020-11-04 08:56:03.524 [info] <0.2506.0> accepting AMQP connection <0.2506.0> (172.18.0.2:34506 -> 172.18.0.6:5672)
> 
> 
> 2020-11-04 08:56:03.591 [info] <0.2506.0> connection <0.2506.0> (172.18.0.2:34506 -> 172.18.0.6:5672): user 'admin' authenticated and granted access to vhost '/'
> 
> 
> 2020-11-04 08:56:03.608 [info] <0.2509.0> connection <0.2509.0> (172.18.0.2:34508 -> 172.18.0.6:5672): user 'admin' authenticated and granted access to vhost '/'
> 
> 
> 2020-11-04 08:56:03.638 [info] <0.2514.0> accepting AMQP connection <0.2514.0> (172.18.0.2:34514 -> 172.18.0.6:5672)
> 
> 
> 2020-11-04 08:56:03.676 [info] <0.2514.0> connection <0.2514.0> (172.18.0.2:34514 -> 172.18.0.6:5672): user 'admin' authenticated and granted access to vhost '/'
> 
> 
> 2020-11-04 08:56:03.850 [info] <0.2533.0> accepting AMQP connection <0.2533.0> (172.18.0.2:34522 -> 172.18.0.6:5672)
> 
> 
> 2020-11-04 08:56:03.879 [info] <0.2536.0> accepting AMQP connection <0.2536.0> (172.18.0.2:34524 -> 172.18.0.6:5672)
> 
> 
> 2020-11-04 08:56:03.884 [info] <0.2533.0> connection <0.2533.0> (172.18.0.2:34522 -> 172.18.0.6:5672): user 'admin' authenticated and granted access to vhost '/'
> 
> 
> 2020-11-04 08:56:03.912 [info] <0.2536.0> connection <0.2536.0> (172.18.0.2:34524 -> 172.18.0.6:5672): user 'admin' authenticated and granted access to vhost '/'
> 
> 
> 2020-11-04 08:56:04.372 [info] <0.2389.0> closing AMQP connection <0.2389.0> (172.18.0.2:34470 -> 172.18.0.6:5672, vhost: '/', user: 'admin')
> 
> 
> 2020-11-04 08:56:04.497 [info] <0.2395.0> closing AMQP connection <0.2395.0> (172.18.0.2:34474 -> 172.18.0.6:5672, vhost: '/', user: 'admin')
> 
> 
> 2020-11-04 08:56:05.033 [info] <0.2424.0> closing AMQP connection <0.2424.0> (172.18.0.2:34486 -> 172.18.0.6:5672, vhost: '/', user: 'admin')
> 
> 
> 2020-11-04 08:56:05.220 [info] <0.2448.0> closing AMQP connection <0.2448.0> (172.18.0.2:34496 -> 172.18.0.6:5672, vhost: '/', user: 'admin')
> 
> 
> 2020-11-04 08:56:08.163 [info] <0.2479.0> closing AMQP connection <0.2479.0> (172.18.0.2:34498 -> 172.18.0.6:5672, vhost: '/', user: 'admin')
> 
> 
> 2020-11-04 08:56:08.917 [info] <0.2533.0> closing AMQP connection <0.2533.0> (172.18.0.2:34522 -> 172.18.0.6:5672, vhost: '/', user: 'admin')
> 
> 
> 2020-11-04 08:56:14.879 [info] <0.2416.0> closing AMQP connection <0.2416.0> (172.18.0.2:34482 -> 172.18.0.6:5672, vhost: '/', user: 'admin')
> 
> 
> 2020-11-04 08:56:14.972 [info] <0.2421.0> closing AMQP connection <0.2421.0> (172.18.0.2:34484 -> 172.18.0.6:5672, vhost: '/', user: 'admin')
>

**Comment by RomaricMourgues** [comment]
Thanks @objeni for all the logs, the file is present in the vendor directory inside the docker image.
The file is here: https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Transport/AbstractSmtpTransport.php
There is some insight here: https://stackoverflow.com/questions/32693528/expected-response-code-220-but-got-code-with-message-in-laravel
Please tell me if it helps

**Comment by objeni** [comment]
I am not able to find that file can you please tell me where is file is located

**Comment by RomaricMourgues** [comment]
If you want to access the file you can do this:
`sudo docker-compose exec php bash` (to enter the container)
Then
`cat /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php`

**Comment by objeni** [comment]
I am getting error like this.Why i am unable to get mail.

```
Fatal error: Uncaught Swift_TransportException: Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first. 192sm1892611pfz.200 - gsmtp
" in /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php on line 457

Swift_TransportException: Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first. 192sm1892611pfz.200 - gsmtp
" in /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php on line 457

Call Stack:
    0.0002     350744   1. {main}() /twake-core/bin/console:0
    0.0743    3036200   2. App\App->runCli() /twake-core/bin/console:9
    0.0744    3036656   3. Common\CommandsManager->run() /twake-core/app/App.php:139
    0.0744    3038368   4. Common\CommandsManager->execute() /twake-core/app/Common/CommandsManager.php:27
    0.0750    3055368   5. Twake\Core\Command\MailsQueueCommand->executeFromManager() /twake-core/app/Common/CommandsManager.php:46
    0.0750    3055368   6. Twake\Core\Command\MailsQueueCommand->execute() /twake-core/app/Common/Commands/ContainerAwareCommand.php:27
    5.5473    8566384   7. Twake\Core\Services\TwakeMailer->sendInternal() /twake-core/src/Twake/Core/Command/MailsQueueCommand.php:69
    5.5646    9383640   8. Twake\Core\Services\TwakeMailer->sendHtml() /twake-core/src/Twake/Core/Services/TwakeMailer.php:100
    5.6172   11114432   9. Swift_Mailer->send() /twake-core/src/Twake/Core/Services/TwakeMailer.php:168
    7.2098   11138752  10. Swift_SmtpTransport->send() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php:71
    7.2106   11147112  11. Swift_SmtpTransport->sendTo() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:206
    7.2106   11147488  12. Swift_SmtpTransport->doMailTransaction() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:516
    7.2110   11148880  13. Swift_SmtpTransport->doDataCommand() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:497
    7.2110   11148880  14. Swift_SmtpTransport->executeCommand() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:390
    7.2110   11148880  15. Swift_SmtpTransport->executeCommand() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php:305
    7.4476   11173184  16. Swift_SmtpTransport->throwException() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:346 
```

**Comment by LawlessWorld** [comment]
> Thanks, this is not good. I think there is an issue with RabbitMQ (we use SQS in production).
> RabbitMQ is managing a lot of things including managing the badges next to channels and sending emails. Both are working so it seems to be related to delayed tasks.
> I cant find a way to list actives routes and tasks on a live Twake RabbitMQ, it could be a good step to know what is happening. Scheduled notifications are prefixed by "scheduled_notifications_".
> We will investigate soon on this point thank you!

Hi romaric, wondering how you guys are looking at a fix for this issue?  This is the only thing that actually keeps us from moving from rocketchat to twake but we have not been able to generate any emails except the initial registrations.  

thanks for the all hard work i see you guys putting in to this!  congrats

**Comment by RomaricMourgues** [comment]
Hello @LawlessWorld we are moving our servers from SQS to RabbitMQ in about 1 month, so we'll have to fix this issue by then. Sorry for the inconvenance in the meanwhile, we do everything we can :)

**Comment by LawlessWorld** [comment]
no worries, I appreciate the update and look forward to it.  

cheers,

**Comment by objeni** [comment]
> I am getting error like this.Why i am unable to get mail.
> 
> ```
> Fatal error: Uncaught Swift_TransportException: Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first. 192sm1892611pfz.200 - gsmtp
> " in /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php on line 457
> 
> Swift_TransportException: Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first. 192sm1892611pfz.200 - gsmtp
> " in /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php on line 457
> 
> Call Stack:
>     0.0002     350744   1. {main}() /twake-core/bin/console:0
>     0.0743    3036200   2. App\App->runCli() /twake-core/bin/console:9
>     0.0744    3036656   3. Common\CommandsManager->run() /twake-core/app/App.php:139
>     0.0744    3038368   4. Common\CommandsManager->execute() /twake-core/app/Common/CommandsManager.php:27
>     0.0750    3055368   5. Twake\Core\Command\MailsQueueCommand->executeFromManager() /twake-core/app/Common/CommandsManager.php:46
>     0.0750    3055368   6. Twake\Core\Command\MailsQueueCommand->execute() /twake-core/app/Common/Commands/ContainerAwareCommand.php:27
>     5.5473    8566384   7. Twake\Core\Services\TwakeMailer->sendInternal() /twake-core/src/Twake/Core/Command/MailsQueueCommand.php:69
>     5.5646    9383640   8. Twake\Core\Services\TwakeMailer->sendHtml() /twake-core/src/Twake/Core/Services/TwakeMailer.php:100
>     5.6172   11114432   9. Swift_Mailer->send() /twake-core/src/Twake/Core/Services/TwakeMailer.php:168
>     7.2098   11138752  10. Swift_SmtpTransport->send() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php:71
>     7.2106   11147112  11. Swift_SmtpTransport->sendTo() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:206
>     7.2106   11147488  12. Swift_SmtpTransport->doMailTransaction() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:516
>     7.2110   11148880  13. Swift_SmtpTransport->doDataCommand() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:497
>     7.2110   11148880  14. Swift_SmtpTransport->executeCommand() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:390
>     7.2110   11148880  15. Swift_SmtpTransport->executeCommand() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php:305
>     7.4476   11173184  16. Swift_SmtpTransport->throwException() /twake-core/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:346 
> ```
> 
> Thanks !

How to solve this error ???

**Comment by objeni** [comment]
???
