### ISSUE TITLE
[Story] Mobile notification

### ISSUE THREAD

**Issue by BenoitTallandier** [Twake/Twake#489]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a user of Twake,
When the system need to send me a notification
And I am not connected on desktop
And I'm logged on the mobile application
And Twake app is not on the foreground or Twake is not open on this discussion
Then I receive a notification on my mobile
```

## Business case
I should be notified, but I am not connected on Twake on desktop, so I receive a push notification on my mobile.

## Criteria
- [ ] When I should receive a notification (like a direct message) an I am not connected on desktop, I should receive a mobile notification
- [ ] Mobile notification are grouped by channel / direct discussion
 
## UI UX Design
Text for push notification
### direct message 
1to1
```
Benoît  
This is my direct message
```
1to3
```
For you, Benoît, Romaric, Alfred  
Benoît : This is my direct message
```
### channel
```
Channel name
Benoît : This is my message in a channel
```

## Related
Epic #350

**Comment by RomaricMourgues** [comment]
Yes, you are right, we can close this one here
