### ISSUE TITLE
[Story] Channel bold when unread messages in it

### ISSUE THREAD

**Issue by BenoitTallandier** [Twake/Twake#516]
## User story summary
[Definition](#Definition)  
[Business case](#Business-case)  
[Criteria](#criteria)  
[UI/UX Design](#UI-UX-design)  
[Notes](#notes)  
[Related](#related)  

## Definition
```gherkin
Given I am a Twake user
When someone send a message in a channel where I am
Then the name of the channel become bold
```

## Business case
I want to know if there is an activity in the channel

## Criteria
- [ ] When someone send a message in a channel, the channel should be bold
- [ ] When I open a channel in bold, It comes back normal
 
## UI UX Design
![image.png](https://images.zenhubusercontent.com/5f06c5a0e15425885ef10c4a/39ab9732-6b55-411f-9acf-d20731bde7ea)
font-weight : 700
color : #444444 (black)

## Related
Epic : #308

**Comment by hantt12** [comment]
Channel name is not always bold as far as I can see
![2021-02-02_15-18.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/c739ea46-a67b-47b2-86ae-894c1f6d9137)
