### ISSUE TITLE
Hide discussion popup should be centered

### ISSUE THREAD

**Issue by stephanevieira75** [Twake/Twake#808]
# Preview
https://images.zenhubusercontent.com/271994210/6d616eea-9c6d-4fca-b9e3-75d78e710c0b/twake__6_.mp4

# To do 
![Capture d’écran de 2021-01-21 12-05-44.png](https://images.zenhubusercontent.com/5f4e3d2d91dca0478164f0b5/e32d35e7-6693-49bc-91be-70c6600027df)

**Comment by rijusougata13** [comment]
hey i want to work on this. can you tell me in which file i have to make changes,where is the componets of this hide discussion tab.?

**Comment by gplutus** [comment]
Question:  which issue or feature does this address?

**Comment by chamerling** [comment]
Hello @rijusougata13,

Everything is in twake/frontend/src/app/scenes/Client/ChannelsBar/Parts/Channel/ChannelMenu.tsx when calling `AlertManager`

**Comment by BenoitTallandier** [comment]
Related to #325
We'll removed the popup
