### ISSUE TITLE
Create Channel > Breaking "Add members" form when the channel name length is over 100 characters

### ISSUE THREAD

**Issue by tlle14** [Twake/Twake#828]
# Precondition
Story: https://github.com/TwakeApp/Twake/issues/321

# Actual Result
When inputting the channel name with the length is over 100 characters, the "add members" form is breaking
![Peek 2021-01-28 10-25.gif](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/d2348bfa-f925-4c12-abea-a6a49bce182b)

# Expected Result
The channel name should have a length limitation 
The "add members" form should be responsive.

# Environment
Chrome Ubuntu

**Comment by RomaricMourgues** [comment]
Solution: @stephanevieira75  Limit channel name length
Will also fix the #834
