### ISSUE TITLE
Join Channel > There has no message when the user has joined the channel

### ISSUE THREAD

**Issue by tlle14** [Twake/Twake#832]
# Precondition
Story: https://github.com/TwakeApp/Twake/issues/314

# Actual Result
The User has joined the channel 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/aa8691ef-b3ad-4d1e-83d6-e86e08826baa)

But there has no message "XXXX join the channel"
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/6eaa05f5-eeda-43cd-a3c8-7841adf3bf75)

# Expected Result
When a user joined the channel, it should display a message `<username> joined the channel`

# Environment
Chrome ubuntu
QA testing environment

**Comment by RomaricMourgues** [comment]
Related to #324 (not yet implemented)
