### ISSUE TITLE
Join Channel > A long channel name breaks the channel list form

### ISSUE THREAD

**Issue by tlle14** [Twake/Twake#834]
# Precondition
Story: https://github.com/TwakeApp/Twake/issues/314

# Actual Result
When there's a channel with a long name, it breaks the channel list form. 
- The `join` button is not in the right place.
- The space between lines is too wide.
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/e54f0170-73d6-4853-9f12-c88efdf05ced)

# Expected Result
The `join` button should be in the right place. 
A long channel name should be trimmed

# Environment
Chrome Ubuntu
QA testing environment

**Comment by RomaricMourgues** [comment]
We limited channel names to 30 characters.
