### ISSUE TITLE
Join Channel > A member is able to search a private channel

### ISSUE THREAD

**Issue by tlle14** [Twake/Twake#853]
# Precondition
Story:https://github.com/TwakeApp/Twake/issues/314
A private channel

# Actual result
A member is able to search a private channel. He is able to click join the channel, but it isn't successful.
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/d2fbdbc3-9fe1-401e-b4b0-a6c0f4d6fb46)

# Expected Result
Please confirm: Is a member able to search a private channel?
If yes, the `join` button should be disabled. 

# Environment
Chrome/ Firefox Ubuntu
QA testing environment

**Comment by RomaricMourgues** [comment]
Member should not see private channels update on its way
