### ISSUE TITLE
Edit Channel > A creator cannot update the channel privacy successfully

### ISSUE THREAD

**Issue by tlle14** [Twake/Twake#860]
# Precondition
Story: https://github.com/TwakeApp/Twake/issues/512
Create a public channel

# Actual Result
When updating the channel privacy, it isn't successful. 
The channel privacy isn't updated with other members
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/f586a24f-921d-43bb-b056-6feab9343680)

# Expected Result
The creator should be able to update channel privacy successfully

# Environment
Chrome/Firefox Ubuntu
QA testing environment

**Comment by RomaricMourgues** [comment]
Fixed
