### ISSUE TITLE
System acts as if user can remove himself from channel

### ISSUE THREAD

**Issue by hantt12** [Twake/Twake#864]
**Describe the bug**
System shows message as if user removed himself successfully from the channel but in fact he is still there

**Expected result**

There are two options:
1. System should not allow user to remove himself from then channel
2. If system allows user to remove himself, it would be like he leaves the channel

![Peek 2021-02-02 18-59.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/2b5c0032-f3c4-4aec-ad40-b24307ba4c07)

**Comment by RomaricMourgues** [comment]
I agree, we should not show this option here, the "Leave channel" in context menu is enough.
