### ISSUE TITLE
Unable to upload file to message

### ISSUE THREAD

**Issue by hantt12** [Twake/Twake#866]
Tested in both Chrome and Firefox

![Peek 2021-02-02 19-59.gif](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/9873b0ef-cf56-45c5-976b-00cc43d43627)

**Comment by RomaricMourgues** [comment]
Configuration was not updated, related to #779
It is fixed now

**Comment by RomaricMourgues** [comment]
@hantt12 can you test it ?
