### ISSUE TITLE
Channel message when user join/leave/is removed is not shown

### ISSUE THREAD

**Issue by hantt12** [Twake/Twake#893]
**Describe the bug**
when user join/leave or is removed from channel, message should be shown

**To Reproduce**
1. Go to a certain channel
2. Try to:
- Join a channel
- Add a user to a channel
- Leave a channel
- Remove a user from a channel

**Expected behavior**
Message should be shown in channel

**Comment by RomaricMourgues** [comment]
Not yet implemented: #888
