### ISSUE TITLE
Twake selfhosted not updating past Current version : 2020.Q3.133

### ISSUE THREAD

**Issue by iFloris** [Twake/Twake#921]
**Describe the bug**
Twake selfhosted does not seem to update past version `Current version : 2020.Q3.133`

**To Reproduce**
We have been using Twake as a tryout pretty much since you open sourced. We have a super-simple shellscript to periodically update to the latest version. This does not update past version `2020.Q3.133`

**Expected behavior**
We expected the update to move to the newer versions.

**Additional context**
The simple script looks like this:
```
#!/bin/bash

cd /opt/ && \
# git clone https://github.com/TwakeApp/Twake.git && \
cd /opt/Twake/twake/ && \
docker-compose stop && \
docker-compose rm -f && \
docker-compose pull && \
docker-compose up -d && \
docker-compose exec nginx yarn build && \
docker system prune -f \
exit 0
```

I also like to follow along with the various branches and noticed that you have been working on a migration path to Q4 in #839, which might be the reason that the update is not actually updating?

Edit 20210224
It seems like you are working on it in #949 :)

Edit 20210228 
The auto update broke our install because we still need to run the migrations 😆 
But at least the install was updated 🚀  I am closing this issue.

**Comment by RomaricMourgues** [comment]
For reference a thread in our community on this subject:
https://community.twake.app/t/twake-not-running-after-update/170/4
