### ISSUE TITLE
Login page is not appearing properly on Safari

### ISSUE THREAD

**Issue by shivam9593** [Twake/Twake#972]
**Describe the bug**

After clicking on **Get Started - It's Free!**, the login/create an account Page is not appearing properly on Safari web browser with some texts misaligned and sign-in button misaligned. 
![Снимок экрана 2021-03-01 в 15 34 35](https://user-images.githubusercontent.com/77721557/109523580-ccdf8c00-7aaf-11eb-8351-28a3fbb6a066.png)

System Details:
MacBook Air (11-inch, Early 2014)
1.4 GHz Intel Core i5
Operating System: Macintosh HD
Web Browser: Safari Version 12.1.2

**Steps to reproduce the behavior:** 
1. Go to twake.app
2. Click on "Get Started - It's free"
3. The webpage is not visible properly

**Comment by RomaricMourgues** [comment]
I close this because it is for Console and they are updating all the UI right now :)
